// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpwgbSAFy90N23EwgmKu0Ji_gFjHDdVXw',
    appId: '1:741661404494:web:3b3ceb139040d70104421f',
    messagingSenderId: '741661404494',
    projectId: 'kandangku-8f67c',
    authDomain: 'kandangku-8f67c.firebaseapp.com',
    storageBucket: 'kandangku-8f67c.firebasestorage.app',
    measurementId: 'G-DQFY2LQ49M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN0N2u2SmpEwAaDTEx16RNanWLkjTtfac',
    appId: '1:741661404494:android:112fe81298873ae304421f',
    messagingSenderId: '741661404494',
    projectId: 'kandangku-8f67c',
    storageBucket: 'kandangku-8f67c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC1EtwHuDprk2uZ2bQ70FoVNvYcpIhWK4',
    appId: '1:741661404494:ios:3814ba202cb2d13d04421f',
    messagingSenderId: '741661404494',
    projectId: 'kandangku-8f67c',
    storageBucket: 'kandangku-8f67c.firebasestorage.app',
    iosBundleId: 'com.example.kandangku',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC1EtwHuDprk2uZ2bQ70FoVNvYcpIhWK4',
    appId: '1:741661404494:ios:3814ba202cb2d13d04421f',
    messagingSenderId: '741661404494',
    projectId: 'kandangku-8f67c',
    storageBucket: 'kandangku-8f67c.firebasestorage.app',
    iosBundleId: 'com.example.kandangku',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpwgbSAFy90N23EwgmKu0Ji_gFjHDdVXw',
    appId: '1:741661404494:web:137b2a2c9e0a2d1704421f',
    messagingSenderId: '741661404494',
    projectId: 'kandangku-8f67c',
    authDomain: 'kandangku-8f67c.firebaseapp.com',
    storageBucket: 'kandangku-8f67c.firebasestorage.app',
    measurementId: 'G-4J05V7MWW0',
  );
}
